project:
  type: website
  output-dir: docs
website:
  title: "notebook "
  navbar:
    logo: "alemka.png"
    background: rgb(249, 220, 92) # now: yellow, previously: 196, 223, 170 a soft green
    foreground: rgb(17, 43, 60) #laci
    left:
      - text: "About me!"
        file: index.qmd    
      - text: "üìù Blog Posts"
        file: index1.qmd
        
    right: 
      - text: "üõ†Ô∏è Apps"
        menu:
          - text: "Test Analyze-R"
            href: https://aliemrekaragul.shinyapps.io/testanalyze-R/  
          - text: "ITP Score Calculator"
            href: https://itp-calculator.com/   
          - text: "Ek≈üi KazaR"
            href: https://aliemrekaragul.shinyapps.io/eksi-kazaR/  
      - text: "‚≠ê Favorite Links"
        menu: 
          - text: "R cheatsheets"
            href: https://posit.cloud/learn/cheat-sheets
          - text: "R 4 D S"
            href: https://r4ds.hadley.nz/          
          - text: "Generate IRT Data"
            href: https://erguldemir.shinyapps.io/ED_GenerateIRTdata/
          - text: "Google Ngram Viewer"
            href: https://books.google.com/ngrams/
      - icon: github
        href: https://github.com/aliemrekaragul
      - icon: linkedin
        href: https://www.linkedin.com/in/ali-emre-karag%C3%BCl/
  cookie-consent:
    type: implied
    style: simple
    palette: light
    prefs-text: "üç™ Cookies"
  google-analytics:
    tracking-id: "G-VJBZWP0G2H"
    anonymize-ip: false
    storage: cookies
    
  page-footer:
    right: "üìà‚ù§Ô∏è‚òï"
    left: "¬© Emre Karag√ºl"
format: 
  html:
    theme: literia  # morph #simplex  # solar #cerulean  #
    css: styles.css
    toc: true
    toc-depth: 4
    toc-title: Contents
    citations-hover: true
    footnotes-hover: true
    # font-family: Gill Sans  #
    mainfont: roboto #monospace
    background: rgb(239, 239, 239) # mat bir  beyaz
    fontcolor: rgb(17, 43, 60) #navy?
    fontsize: 1.1em
    linestretch: 1.5
    code-tools: false
    code-block-border-left: true
    code-link: true
    code-fold: show
    # code-block-bg:  rgb(224, 216, 176) # yellowish brown gibi bi≈üi
editor: visual

